Code signing tweak, #79

diff --git a/packaging/mac/scripts/postinstall b/packaging/mac/scripts/postinstall
--- a/packaging/mac/scripts/postinstall
+++ b/packaging/mac/scripts/postinstall
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-#set -e # compileall can fail the installation
+#set -e # compileall can fail the installation 
 
 echo "Starting postinstall"
 echo "Thonny was installed to $2"
